commit 72770086dd279f62cc2763fa08480db59c427870
Author: Evgeny Potemkin <evgeny.potemkin@oracle.com>
Date:   Tue Nov 5 15:45:33 2013 +0400

    Bug#17458169: CRASH WITH FAULTY EXISTS .. AGAINST IN SUBQUERY
    Fix for the bug#16509874 cleaned select_lex's links after excluding it from
    select_lex tree and updated links of outer_context of underlying
    select_lex'es. But outer_context of fake_select_lex wasn't updated and
    caused dereferencing NULL and crash.
    Now st_select_lex_unit::exclude_level updated outer_context of
    fake_select_lex too.

diff --git a/sql/sql_lex.cc b/sql/sql_lex.cc
index 3abb818ea03..bc5d7e9f0ff 100644
--- a/sql/sql_lex.cc
+++ b/sql/sql_lex.cc
@@ -2187,6 +2187,9 @@ void st_select_lex_unit::exclude_level()
         if (s->context.outer_context == &sl->context)
           s->context.outer_context= sl->context.outer_context;
       }
+      if (u->fake_select_lex &&
+          u->fake_select_lex->context.outer_context == &sl->context)
+        u->fake_select_lex->context.outer_context= sl->context.outer_context;
       u->master= master;
       last= &(u->next);
     }

